export {Home} from "../partial/Home"
export {About} from "../partial/About"
export {Menu} from "../partial/Menu"
export {Events} from "../partial/Events"
export {Book} from "../partial/Book"
export {BreakFastMenu} from "../partial/BreakFastMenu"
export {SpecialtyMenu} from "../partial/SpecialtyMenu"
export {SeaFoodMenu} from "../partial/SeaFoodMenu"
export {BeefMenu} from "../partial/BeefMenu"
export {ChickenMenu} from "../partial/ChickenMenu"
export {VegetableMenu} from "../partial/VegetableMenu"
export {NoodlesMenu} from "../partial/NoodlesMenu"
export {RiceMenu} from "../partial/RiceMenu"
export {DessertsMenu} from "../partial/DessertsMenu"
export {BeveragesMenu} from "../partial/BeveragesMenu"


export {PageNotFound} from "../partial/PageNotFound"